main-lobby: {}
void-kill-height: 0
void-teleport-height: 0
trap-radius: 10
chat-format: "[{team_color}{team_name}] {player_name}: {message}"

database:
    type: sqlite # sqlite or mysql
    save-interval: 5 # minutes between automatic saves
    mysql:
      host: localhost
      port: 3306
      database: bedwars
      username: root
      password: ""
      useSSL: false

bungeecord:
  enabled: false
  lobby-server-name: "lobby"

mobs:
  iron-golem:
    damage: 4.0
