void-kill-height: 0
trap-radius: 10

database:
    type: sqlite # sqlite or mysql
    save-interval: 5 # minutes between automatic saves
    mysql:
      host: localhost
      port: 3306
      database: bedwars
      username: root
      password: ""
      useSSL: false

mobs:
  iron-golem:
    damage: 4.0

generator-holograms:
  diamond: "&bDiamant dans &f{time}s"
  emerald: "&aÉmeraude dans &f{time}s"
