void-kill-height: 0
trap-radius: 10

database:
    type: sqlite # sqlite or mysql
    save-interval: 5 # minutes between automatic saves
    mysql:
      host: localhost
      port: 3306
      database: bedwars
      username: root
      password: ""
      useSSL: false

mobs:
  iron-golem:
    damage: 4.0

generator-holograms:
  enabled: true
  offset-y: 2.5 # Hauteur de l'hologramme au-dessus du générateur
  formats:
    DIAMOND:
      - "&b&lDiamants"
      - "&fApparaît dans &a{time}s"
    EMERALD:
      - "&2&lÉmeraudes"
      - "&fApparaît dans &a{time}s"
