name: HeneriaBedwars
version: ${project.version}
main: com.heneria.bedwars.HeneriaBedwars
api-version: '1.21'
author: tomashb
softdepend: [Vault]

commands:
  bedwars:
    description: Commande principale de HeneriaBedwars.
    aliases: [bw, hbw]
  spawn:
    description: Téléporte au lobby BedWars.
  hub:
    description: Rejoint le serveur lobby principal.

permissions:
  heneriabw.admin:
    description: Donne accès à toutes les commandes d'administration de HeneriaBedwars.
    default: op
  heneriabw.admin.stats:
    description: Permet de voir les statistiques des autres joueurs.
    default: op
  heneriabw.admin.setmainlobby:
    description: Définit le lobby principal BedWars.
    default: op
  heneriabw.admin.setjoinnpc:
    description: Place un PNJ de sélection d'arène.
    default: op
  heneriabw.admin.setshopnpc:
    description: Place un PNJ de boutique pour une équipe.
    default: op
  heneriabw.admin.bypass:
    description: Permet d'activer le mode bypass pour modifier la carte.
    default: op
  heneriabw.player.shop:
    description: Permet d'ouvrir la boutique de cosmétiques.
    default: true
