name: HeneriaBedwars
version: ${project.version}
main: com.heneria.bedwars.HeneriaBedwars
api-version: '1.21'
author: tomashb

softdepend: [DecentHolograms]

commands:
  bedwars:
    description: Commande principale de HeneriaBedwars.
    aliases: [bw, hbw]

permissions:
  heneriabw.admin:
    description: Donne accès à toutes les commandes d'administration de HeneriaBedwars.
    default: op
  heneriabw.admin.stats:
    description: Permet de voir les statistiques des autres joueurs.
    default: op
